/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgab;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import static sgab.ConexionMySQL.rs;
import sgab.MenuPrincipal;

/**
 *
 * @author Francisco Hernandez
 */
public class Login extends javax.swing.JFrame {
    private static String usuario = "";
    private static String contra = "";
    private char pass[];
    public static Connection con = null;
    private MenuPrincipal mp;
    private Timer tiempo;
    private int cont;
    private final static int TWO_SECOND=5;
    Validar val = new Validar();
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Iniciar Sesión");
        this.setResizable(false);
        barraPro.setVisible(false);
        UIManager.put( "nimbusOrange", new Color( 30, 165, 14 ) );
        //38,139,210
    }
    class TimerListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            cont++;
            barraPro.setValue(cont);
            if(cont == 50){
                tiempo.stop();
                esconder(); 
                mp = new MenuPrincipal(usuario,contra);
                mp.setVisible(true);
                setVisible(false);
                dispose();
            }           
        }      
    }
    public void esconder(){this.setVisible(false);}
    public void activar(){tiempo.start();}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextUsuario = new javax.swing.JTextField();
        eUsuario = new javax.swing.JLabel();
        eContra = new javax.swing.JLabel();
        bIngresar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        eIniciarSesion = new javax.swing.JLabel();
        TextContra = new javax.swing.JPasswordField();
        eImagen = new javax.swing.JLabel();
        barraPro = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuarioActionPerformed(evt);
            }
        });
        TextUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextUsuarioKeyTyped(evt);
            }
        });

        eUsuario.setText("Usuario:");

        eContra.setText("Contraseña:");

        bIngresar.setText("Ingresar");
        bIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        eIniciarSesion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        eIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eIniciarSesion.setText("INICIAR SESIÓN");

        TextContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextContraKeyTyped(evt);
            }
        });

        eImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgab/img/administrator.png"))); // NOI18N

        barraPro.setBackground(new java.awt.Color(51, 255, 0));
        barraPro.setMaximum(50);
        barraPro.setStringPainted(true);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Biblioteca Municipal de San Andrés Ixtlán");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(eImagen)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bIngresar)
                        .addGap(79, 79, 79)
                        .addComponent(bSalir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(barraPro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(eContra)
                                .addComponent(eUsuario))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextContra, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(eIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eUsuario)
                            .addComponent(TextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eContra)
                            .addComponent(TextContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(barraPro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(eImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIngresar)
                    .addComponent(bSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarActionPerformed
        usuario = TextUsuario.getText();
        pass = TextContra.getPassword();
        contra = new String(pass);
        con = null;
        if(UConnection.getLogin(usuario, contra) == 1)
        {
            barraPro.setVisible(true);
            cont=-1;
            barraPro.setValue(0);
            barraPro.setStringPainted(true);
            tiempo = new Timer(TWO_SECOND, new TimerListener());
            activar();
        }
        else
            JOptionPane.showMessageDialog(null, "Datos Incorrectos");
    }//GEN-LAST:event_bIngresarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void TextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsuarioActionPerformed

    private void TextContraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextContraKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            usuario = TextUsuario.getText();
            pass = TextContra.getPassword();
            contra = new String(pass);
            try {
                if(UConnection.getLogin(usuario, contra) == 1) // valUsuario(usuario, contra)
            {
                barraPro.setVisible(true);
                cont=-1;
                barraPro.setValue(0);
                barraPro.setStringPainted(true);
                tiempo = new Timer(TWO_SECOND, new TimerListener());
                activar();
            }
            else
                JOptionPane.showMessageDialog(null, "Datos Incorrectos");
            } catch (Exception e) {
            }
            
        }
    }//GEN-LAST:event_TextContraKeyTyped

    private void TextUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextUsuarioKeyTyped
                if (val.letrasNumeros(evt.getKeyChar()) || TextUsuario.getText().length() == 40) {
            evt.consume();
        }
    }//GEN-LAST:event_TextUsuarioKeyTyped

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TextContra;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JButton bIngresar;
    private javax.swing.JButton bSalir;
    private javax.swing.JProgressBar barraPro;
    private javax.swing.JLabel eContra;
    private javax.swing.JLabel eImagen;
    private javax.swing.JLabel eIniciarSesion;
    private javax.swing.JLabel eUsuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
