/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgab;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.FlowLayout;
import javax.swing.Box;
import javax.swing.JOptionPane;

/**
 *
 * @author FranciscoHernandez
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private LibrosPanel librosp;
    private InicioPanel iniciop;
    private UsuariosPanel usuariosp;
    private VisitasPanel visitasp;
    private RegistrosPanel registrosp;
    private PrestamosPanel prestamosp;
    private MultasPanel multasp;
    private ReportesPanel reportesp;
    private SeguridadPanel seguridadp;
    private ActividadesPanel actividadesp;
    private Color colorPersonalizado = new Color(153, 154, 155);
    private static String user = "";
    private static String password = "";
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(String user,String password) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema Gestor y Administrador Bibliotecario");
        this.user = user;
        this.password = password;
        formularioPanel.setLayout(new BorderLayout());
        inicioB.setOpaque(false);
        inicioB.setContentAreaFilled(false);
        inicioB.setBorderPainted(false);
        librosB.setOpaque(false);
        librosB.setContentAreaFilled(false);
        librosB.setBorderPainted(false);
        usuariosB.setOpaque(false);
        usuariosB.setContentAreaFilled(false);
        usuariosB.setBorderPainted(false);
        prestamosB.setOpaque(false);
        prestamosB.setContentAreaFilled(false);
        prestamosB.setBorderPainted(false);
        visitasB.setOpaque(false);
        visitasB.setContentAreaFilled(false);
        visitasB.setBorderPainted(false);
        multasB.setOpaque(false);
        multasB.setContentAreaFilled(false);
        multasB.setBorderPainted(false);
        actividadesB.setOpaque(false);
        actividadesB.setContentAreaFilled(false);
        actividadesB.setBorderPainted(false);
        registrosB.setOpaque(false);
        registrosB.setContentAreaFilled(false);
        registrosB.setBorderPainted(false);
        reportesB.setOpaque(false);
        reportesB.setContentAreaFilled(false);
        reportesB.setBorderPainted(false);
        seguridadB.setOpaque(false);
        seguridadB.setContentAreaFilled(false);
        seguridadB.setBorderPainted(false);
        salirBtn.setOpaque(false);
        salirBtn.setContentAreaFilled(false);
        salirBtn.setBorderPainted(false);
        
        iniciop = new InicioPanel(user);
        formularioPanel.removeAll();
        formularioPanel.add(iniciop,"Center");
        formularioPanel.revalidate();
        formularioPanel.repaint();
        usuarioMenuBar.setText(user);
       // menuBar.add(Box.createHorizontalGlue());
        menuBar.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        formularioPanel = new javax.swing.JPanel();
        menuBotonesPanel = new javax.swing.JPanel();
        librosB = new javax.swing.JButton();
        inicioB = new javax.swing.JButton();
        usuariosB = new javax.swing.JButton();
        prestamosB = new javax.swing.JButton();
        visitasB = new javax.swing.JButton();
        multasB = new javax.swing.JButton();
        actividadesB = new javax.swing.JButton();
        reportesB = new javax.swing.JButton();
        registrosB = new javax.swing.JButton();
        seguridadB = new javax.swing.JButton();
        salirBtn = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        acercaDeMenu = new javax.swing.JMenuItem();
        usuarioMenuBar = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        formularioPanel.setBackground(new java.awt.Color(255, 153, 255));
        formularioPanel.setPreferredSize(new java.awt.Dimension(909, 0));

        javax.swing.GroupLayout formularioPanelLayout = new javax.swing.GroupLayout(formularioPanel);
        formularioPanel.setLayout(formularioPanelLayout);
        formularioPanelLayout.setHorizontalGroup(
            formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1084, Short.MAX_VALUE)
        );
        formularioPanelLayout.setVerticalGroup(
            formularioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menuBotonesPanel.setBackground(new java.awt.Color(0, 32, 77));

        librosB.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        librosB.setForeground(new java.awt.Color(255, 255, 255));
        librosB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgab/img/book.png"))); // NOI18N
        librosB.setText("LIBROS");
        librosB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        librosB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                librosBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                librosBMouseExited(evt);
            }
        });
        librosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosBActionPerformed(evt);
            }
        });

        inicioB.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        inicioB.setForeground(new java.awt.Color(255, 255, 255));
        inicioB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgab/img/home.png"))); // NOI18N
        inicioB.setText("INICIO");
        inicioB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inicioB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inicioBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inicioBMouseExited(evt);
            }
        });
        inicioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioBActionPerformed(evt);
            }
        });

        usuariosB.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        usuariosB.setForeground(new java.awt.Color(255, 255, 255));
        usuariosB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgab/img/group.png"))); // NOI18N
        usuariosB.setText("USUARIOS");
        usuariosB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usuariosB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usuariosBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usuariosBMouseExited(evt);
            }
        });
        usuariosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosBActionPerformed(evt);
            }
        });

        prestamosB.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        prestamosB.setForeground(new java.awt.Color(255, 255, 255));
        prestamosB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgab/img/hand_handshake.png"))); // NOI18N
        prestamosB.setText("PRÉSTAMOS");
        prestamosB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        prestamosB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prestamosBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prestamosBMouseExited(evt);
            }
        });
        prestamosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamosBActionPerformed(evt);
            }
        });

        visitasB.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        visitasB.setForeground(new java.awt.Color(255, 255, 255));
        visitasB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgab/img/location.png"))); // NOI18N
        visitasB.setText("VISITAS");
        visitasB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        visitasB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                visitasBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                visitasBMouseExited(evt);
            }
        });
        visitasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitasBActionPerformed(evt);
            }
        });

        multasB.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        multasB.setForeground(new java.awt.Color(255, 255, 255));
        multasB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgab/img/currency_dollar_sign.png"))); // NOI18N
        multasB.setText("MULTAS");
        multasB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        multasB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                multasBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                multasBMouseExited(evt);
            }
        });
        multasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multasBActionPerformed(evt);
            }
        });

        actividadesB.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        actividadesB.setForeground(new java.awt.Color(255, 255, 255));
        actividadesB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgab/img/calendar.png"))); // NOI18N
        actividadesB.setText("ACTIVIDADES");
        actividadesB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        actividadesB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                actividadesBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                actividadesBMouseExited(evt);
            }
        });
        actividadesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actividadesBActionPerformed(evt);
            }
        });

        reportesB.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        reportesB.setForeground(new java.awt.Color(255, 255, 255));
        reportesB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgab/img/document.png"))); // NOI18N
        reportesB.setText("REPORTES");
        reportesB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reportesB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportesBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportesBMouseExited(evt);
            }
        });
        reportesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesBActionPerformed(evt);
            }
        });

        registrosB.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        registrosB.setForeground(new java.awt.Color(255, 255, 255));
        registrosB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgab/img/file.png"))); // NOI18N
        registrosB.setText("REGISTROS");
        registrosB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        registrosB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrosBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrosBMouseExited(evt);
            }
        });
        registrosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrosBActionPerformed(evt);
            }
        });

        seguridadB.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        seguridadB.setForeground(new java.awt.Color(255, 255, 255));
        seguridadB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgab/img/security.png"))); // NOI18N
        seguridadB.setText("SEGURIDAD");
        seguridadB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seguridadB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seguridadBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seguridadBMouseExited(evt);
            }
        });
        seguridadB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguridadBActionPerformed(evt);
            }
        });

        salirBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        salirBtn.setForeground(new java.awt.Color(255, 255, 255));
        salirBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgab/img/disconnect.png"))); // NOI18N
        salirBtn.setText("SALIR");
        salirBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirBtnMouseExited(evt);
            }
        });
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBotonesPanelLayout = new javax.swing.GroupLayout(menuBotonesPanel);
        menuBotonesPanel.setLayout(menuBotonesPanelLayout);
        menuBotonesPanelLayout.setHorizontalGroup(
            menuBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actividadesB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(multasB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(visitasB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reportesB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(registrosB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(seguridadB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(salirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(librosB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(usuariosB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(prestamosB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inicioB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuBotonesPanelLayout.setVerticalGroup(
            menuBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBotonesPanelLayout.createSequentialGroup()
                .addComponent(inicioB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(librosB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuariosB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prestamosB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visitasB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(multasB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(actividadesB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrosB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportesB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seguridadB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jMenu4.setText("Opciones");
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        acercaDeMenu.setText("Acerca de");
        acercaDeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaDeMenuActionPerformed(evt);
            }
        });
        jMenu4.add(acercaDeMenu);

        menuBar.add(jMenu4);

        usuarioMenuBar.setText("Usuario");

        jMenuItem2.setText("Cerrar Sesión");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        usuarioMenuBar.add(jMenuItem2);

        menuBar.add(usuarioMenuBar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuBotonesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formularioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBotonesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formularioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void librosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosBActionPerformed
        librosp = new LibrosPanel(user,password);

        formularioPanel.removeAll();
        formularioPanel.add(librosp,"Center");
        formularioPanel.revalidate();
        formularioPanel.repaint();
    }//GEN-LAST:event_librosBActionPerformed

    private void inicioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioBActionPerformed
        iniciop = new InicioPanel(user);

        formularioPanel.removeAll();
        formularioPanel.add(iniciop,"Center");
        formularioPanel.revalidate();
        formularioPanel.repaint();
    }//GEN-LAST:event_inicioBActionPerformed

    private void visitasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitasBActionPerformed
        visitasp = new VisitasPanel(user,password);

        formularioPanel.removeAll();
        formularioPanel.add(visitasp,"Center");
        formularioPanel.revalidate();
        formularioPanel.repaint();
    }//GEN-LAST:event_visitasBActionPerformed

    private void inicioBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioBMouseExited
        inicioB.setOpaque(false);
        inicioB.setContentAreaFilled(false);
        inicioB.setBorderPainted(false);
        inicioB.setForeground(Color.WHITE);
    }//GEN-LAST:event_inicioBMouseExited

    private void librosBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_librosBMouseEntered
        librosB.setOpaque(true);
        librosB.setContentAreaFilled(true);
        librosB.setBorderPainted(true);    
        librosB.setBackground(colorPersonalizado);
        librosB.setForeground(Color.BLACK);
    }//GEN-LAST:event_librosBMouseEntered

    private void librosBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_librosBMouseExited
        librosB.setOpaque(false);
        librosB.setContentAreaFilled(false);
        librosB.setBorderPainted(false);
        librosB.setForeground(Color.WHITE);
    }//GEN-LAST:event_librosBMouseExited

    private void inicioBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioBMouseEntered
        inicioB.setOpaque(true);
        inicioB.setContentAreaFilled(true);
        inicioB.setBorderPainted(true);    
        inicioB.setBackground(colorPersonalizado);
        inicioB.setForeground(Color.BLACK);
    }//GEN-LAST:event_inicioBMouseEntered

    private void usuariosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosBActionPerformed
        usuariosp = new UsuariosPanel(user,password);

        formularioPanel.removeAll();
        formularioPanel.add(usuariosp,"Center");
        formularioPanel.revalidate();
        formularioPanel.repaint();
    }//GEN-LAST:event_usuariosBActionPerformed

    private void usuariosBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariosBMouseEntered
        usuariosB.setOpaque(true);
        usuariosB.setContentAreaFilled(true);
        usuariosB.setBorderPainted(true);    
        usuariosB.setBackground(colorPersonalizado);
        usuariosB.setForeground(Color.BLACK);
    }//GEN-LAST:event_usuariosBMouseEntered

    private void usuariosBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariosBMouseExited
        usuariosB.setOpaque(false);
        usuariosB.setContentAreaFilled(false);
        usuariosB.setBorderPainted(false);
        usuariosB.setForeground(Color.WHITE);
    }//GEN-LAST:event_usuariosBMouseExited

    private void prestamosBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prestamosBMouseEntered
        prestamosB.setOpaque(true);
        prestamosB.setContentAreaFilled(true);
        prestamosB.setBorderPainted(true);    
        prestamosB.setBackground(colorPersonalizado);
        prestamosB.setForeground(Color.BLACK);
    }//GEN-LAST:event_prestamosBMouseEntered

    private void prestamosBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prestamosBMouseExited
        prestamosB.setOpaque(false);
        prestamosB.setContentAreaFilled(false);
        prestamosB.setBorderPainted(false);
        prestamosB.setForeground(Color.WHITE);
    }//GEN-LAST:event_prestamosBMouseExited

    private void visitasBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitasBMouseEntered
        visitasB.setOpaque(true);
        visitasB.setContentAreaFilled(true);
        visitasB.setBorderPainted(true);    
        visitasB.setBackground(colorPersonalizado);
        visitasB.setForeground(Color.BLACK);
    }//GEN-LAST:event_visitasBMouseEntered

    private void visitasBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitasBMouseExited
        visitasB.setOpaque(false);
        visitasB.setContentAreaFilled(false);
        visitasB.setBorderPainted(false);
        visitasB.setForeground(Color.WHITE);
    }//GEN-LAST:event_visitasBMouseExited

    private void multasBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multasBMouseEntered
        multasB.setOpaque(true);
        multasB.setContentAreaFilled(true);
        multasB.setBorderPainted(true);    
        multasB.setBackground(colorPersonalizado);
        multasB.setForeground(Color.BLACK);
    }//GEN-LAST:event_multasBMouseEntered

    private void multasBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multasBMouseExited
        multasB.setOpaque(false);
        multasB.setContentAreaFilled(false);
        multasB.setBorderPainted(false);
        multasB.setForeground(Color.WHITE);
    }//GEN-LAST:event_multasBMouseExited

    private void actividadesBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actividadesBMouseEntered
        actividadesB.setOpaque(true);
        actividadesB.setContentAreaFilled(true);
        actividadesB.setBorderPainted(true);    
        actividadesB.setBackground(colorPersonalizado);
        actividadesB.setForeground(Color.BLACK);
    }//GEN-LAST:event_actividadesBMouseEntered

    private void actividadesBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actividadesBMouseExited
        actividadesB.setOpaque(false);
        actividadesB.setContentAreaFilled(false);
        actividadesB.setBorderPainted(false);
        actividadesB.setForeground(Color.WHITE);
    }//GEN-LAST:event_actividadesBMouseExited

    private void registrosBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrosBMouseEntered
        registrosB.setOpaque(true);
        registrosB.setContentAreaFilled(true);
        registrosB.setBorderPainted(true);    
        registrosB.setBackground(colorPersonalizado);
        registrosB.setForeground(Color.BLACK);
    }//GEN-LAST:event_registrosBMouseEntered

    private void registrosBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrosBMouseExited
        registrosB.setOpaque(false);
        registrosB.setContentAreaFilled(false);
        registrosB.setBorderPainted(false);
        registrosB.setForeground(Color.WHITE);
    }//GEN-LAST:event_registrosBMouseExited

    private void reportesBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportesBMouseEntered
        reportesB.setOpaque(true);
        reportesB.setContentAreaFilled(true);
        reportesB.setBorderPainted(true);    
        reportesB.setBackground(colorPersonalizado);
        reportesB.setForeground(Color.BLACK);
    }//GEN-LAST:event_reportesBMouseEntered

    private void reportesBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportesBMouseExited
        reportesB.setOpaque(false);
        reportesB.setContentAreaFilled(false);
        reportesB.setBorderPainted(false);
        reportesB.setForeground(Color.WHITE);
    }//GEN-LAST:event_reportesBMouseExited

    private void seguridadBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seguridadBMouseEntered
        seguridadB.setOpaque(true);
        seguridadB.setContentAreaFilled(true);
        seguridadB.setBorderPainted(true);    
        seguridadB.setBackground(colorPersonalizado);
        seguridadB.setForeground(Color.BLACK);
    }//GEN-LAST:event_seguridadBMouseEntered

    private void seguridadBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seguridadBMouseExited
        seguridadB.setOpaque(false);
        seguridadB.setContentAreaFilled(false);
        seguridadB.setBorderPainted(false);
        seguridadB.setForeground(Color.WHITE);
    }//GEN-LAST:event_seguridadBMouseExited

    private void salirBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBtnMouseEntered
        salirBtn.setOpaque(true);
        salirBtn.setContentAreaFilled(true);
        salirBtn.setBorderPainted(true);    
        salirBtn.setBackground(colorPersonalizado);
        salirBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_salirBtnMouseEntered

    private void salirBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBtnMouseExited
        salirBtn.setOpaque(false);
        salirBtn.setContentAreaFilled(false);
        salirBtn.setBorderPainted(false);
        salirBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_salirBtnMouseExited

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        setVisible(false);
        dispose();
        Login lg = new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_salirBtnActionPerformed

    private void registrosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrosBActionPerformed
        registrosp = new RegistrosPanel(user,password);

        formularioPanel.removeAll();
        formularioPanel.add(registrosp,"Center");
        formularioPanel.revalidate();
        formularioPanel.repaint();
    }//GEN-LAST:event_registrosBActionPerformed

    private void prestamosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamosBActionPerformed
        prestamosp = new PrestamosPanel(user,password);

        formularioPanel.removeAll();
        formularioPanel.add(prestamosp,"Center");
        formularioPanel.revalidate();
        formularioPanel.repaint();
    }//GEN-LAST:event_prestamosBActionPerformed

    private void multasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multasBActionPerformed
        multasp = new MultasPanel(user,password);

        formularioPanel.removeAll();
        formularioPanel.add(multasp,"Center");
        formularioPanel.revalidate();
        formularioPanel.repaint();
    }//GEN-LAST:event_multasBActionPerformed

    private void reportesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesBActionPerformed
        reportesp = new ReportesPanel(user,password);

        formularioPanel.removeAll();
        formularioPanel.add(reportesp,"Center");
        formularioPanel.revalidate();
        formularioPanel.repaint();
    }//GEN-LAST:event_reportesBActionPerformed

    private void actividadesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actividadesBActionPerformed
        actividadesp = new ActividadesPanel(user,password);

        formularioPanel.removeAll();
        formularioPanel.add(actividadesp,"Center");
        formularioPanel.revalidate();
        formularioPanel.repaint();
    }//GEN-LAST:event_actividadesBActionPerformed

    private void seguridadBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguridadBActionPerformed
        seguridadp = new SeguridadPanel(user,password);

        formularioPanel.removeAll();
        formularioPanel.add(seguridadp,"Center");
        formularioPanel.revalidate();
        formularioPanel.repaint();
    }//GEN-LAST:event_seguridadBActionPerformed

    private void acercaDeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaDeMenuActionPerformed
        JOptionPane.showMessageDialog(null, "Versión 1.0\nDesarrollado por Thinking Code, Inc");
    }//GEN-LAST:event_acercaDeMenuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        setVisible(false);
        dispose();
        Login lg = new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal(user,password).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acercaDeMenu;
    private javax.swing.JButton actividadesB;
    private javax.swing.JPanel formularioPanel;
    private javax.swing.JButton inicioB;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton librosB;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel menuBotonesPanel;
    private javax.swing.JButton multasB;
    private javax.swing.JButton prestamosB;
    private javax.swing.JButton registrosB;
    private javax.swing.JButton reportesB;
    private javax.swing.JButton salirBtn;
    private javax.swing.JButton seguridadB;
    private javax.swing.JMenu usuarioMenuBar;
    private javax.swing.JButton usuariosB;
    private javax.swing.JButton visitasB;
    // End of variables declaration//GEN-END:variables
}
