/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgab;

import sgab.Seleccion;
import java.awt.Component;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author FranciscoHernandez
 */
public class SeguridadPanel extends javax.swing.JPanel {

    /**
     * Creates new form SeguridadPanel
     */
    private Connection con = null;
    private String host = "localhost";
    private String user = "";
    private String password = "";
    private String bd = "biblioteca";
    private String path = "";
    //private String ruta = "";
    private static String respaldar = "";
    private static String restaurar = "";
    private String extension = ".sql";
    Statement stmt;
    Runtime rt = Runtime.getRuntime();
    SeguridadPanel Sp;

    public SeguridadPanel(String user,String password) {
        initComponents();
        this.user = user;
        this.password = password;
        //respaldar = "C:/xampp/mysql/bin/mysqldump -u"+user+" -p"+password+" biblioteca";
        //restaurar = "C:/xampp/mysql/bin/mysql -u"+user+" -p"+password+" biblioteca";
        respaldar = "mysqldump -u"+user+" -p"+password+" biblioteca";
        restaurar = "mysql -u"+user+" -p"+password+" biblioteca";
    txtRutaResp.setEditable(false);
    txtRutaRest.setEditable(false);
    }

    public void mysqlComandos(String cad) {
        try {
            con = UConnection.getConnectionSimple(user,password);
            stmt = (Statement) con.createStatement();
            stmt.execute(cad);
            stmt.close();
            UConnection.cerrarV2();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private static void respaldar(String ruta) {
        try {
            Process p = Runtime
                    .getRuntime()
                    .exec(respaldar);
            new HiloLector(p.getErrorStream()).start();
            InputStream is = p.getInputStream();
            FileOutputStream fos = new FileOutputStream(ruta);
            byte[] buffer = new byte[1000];

            int leido = is.read(buffer);
            while (leido > 0) {
                fos.write(buffer, 0, leido);
                leido = is.read(buffer);
            }

            fos.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static void restaurar(String ruta) {
        try {
            Process p = Runtime
                    .getRuntime()
                    .exec(restaurar);
            new HiloLector(p.getErrorStream()).start();
            OutputStream os = p.getOutputStream();
            FileInputStream fis = new FileInputStream(ruta);
            byte[] buffer = new byte[1000];

            int leido = fis.read(buffer);
            while (leido > 0) {
                os.write(buffer, 0, leido);
                leido = fis.read(buffer);
            }

            os.flush();
            os.close();
            fis.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRutaResp = new javax.swing.JTextField();
        ExaminarRespJButton = new javax.swing.JButton();
        RespaldarBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ExaminarRespButton = new javax.swing.JButton();
        txtRutaRest = new javax.swing.JTextField();
        RestaurarBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(909, 614));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SEGURIDAD");

        jLabel2.setText("Ruta:");

        ExaminarRespJButton.setText("Examinar");
        ExaminarRespJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExaminarRespJButtonActionPerformed(evt);
            }
        });

        RespaldarBtn.setText("Crear Respaldo");
        RespaldarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespaldarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RespaldarBtn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRutaResp, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ExaminarRespJButton)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRutaResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExaminarRespJButton))
                .addGap(31, 31, 31)
                .addComponent(RespaldarBtn)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Respaldar", jPanel1);

        jLabel3.setText("Ruta:");

        ExaminarRespButton.setText("Examinar");
        ExaminarRespButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExaminarRespButtonActionPerformed(evt);
            }
        });

        RestaurarBtn.setText("Restaurar datos");
        RestaurarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaurarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RestaurarBtn)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtRutaRest, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExaminarRespButton)))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ExaminarRespButton)
                    .addComponent(txtRutaRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(RestaurarBtn)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Restaurar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ExaminarRespJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExaminarRespJButtonActionPerformed
        Seleccion o = new Seleccion();
        o.ResetFiltros();
        File file = o.guardar(this);
        if (file != null) {
            String cad = file.getAbsolutePath();
            txtRutaResp.setText(cad);
        }
    }//GEN-LAST:event_ExaminarRespJButtonActionPerformed


    private void ExaminarRespButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExaminarRespButtonActionPerformed
        Seleccion o = new Seleccion();
        File file = o.Abrir(this);
        if (file != null) {
            String cad = file.getAbsolutePath();
            txtRutaRest.setText(cad);
        }


    }//GEN-LAST:event_ExaminarRespButtonActionPerformed

    private void RespaldarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespaldarBtnActionPerformed
        if (txtRutaResp.getText().length() > 0) {
            File file;
            file = new File(txtRutaResp.getText());
            path = file.getAbsolutePath() + extension;
            //System.out.println(""+path);
            int c = JOptionPane.showConfirmDialog(Sp, "¿Desea crear una Copia de Seguridad en esta ruta? \n" + path, "Mensaje de Confirmacion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (c == JOptionPane.YES_OPTION) {
                respaldar(path);
                JOptionPane.showMessageDialog(Sp, "Respaldo creado en \n" + file.getPath());
                //this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Complete todos los campos");
        }
    }//GEN-LAST:event_RespaldarBtnActionPerformed

    private void RestaurarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaurarBtnActionPerformed
        if (txtRutaRest.getText().length() > 0) {
            File file;
            file = new File(txtRutaRest.getText());
            path = file.getAbsolutePath();
            int c = JOptionPane.showConfirmDialog(Sp, "¿Desea Restaurar esta Base de datos?", "mensaje de confirmacion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (c == JOptionPane.YES_OPTION) {
                mysqlComandos("drop database if exists biblioteca;");
                mysqlComandos("create database biblioteca");
                restaurar(path);
                JOptionPane.showMessageDialog(Sp, "La Base de Datos ha sido Restaurada Correctamente");
                //this.dispose();
            }
        }
    }//GEN-LAST:event_RestaurarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExaminarRespButton;
    private javax.swing.JButton ExaminarRespJButton;
    private javax.swing.JButton RespaldarBtn;
    private javax.swing.JButton RestaurarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtRutaResp;
    private javax.swing.JTextField txtRutaRest;
    // End of variables declaration//GEN-END:variables

    //private void dispose() {
    //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}
}
